// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using notification.backend.Infrastructure.Database;

#nullable disable

namespace notification.backend.Infrastructure.Database.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    [Migration("20260329223526_InitialNotificationSchema")]
    partial class InitialNotificationSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("notification.backend.Domain.Models.ProcessedMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("EVENT_TYPE");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MESSAGE_ID");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("PROCESSED_AT");

                    b.HasKey("Id");

                    b.HasIndex("MessageId", "EventType")
                        .IsUnique()
                        .HasDatabaseName("UX_PROCESSED_MESSAGES_MSG_TYPE");

                    b.ToTable("PROCESSED_MESSAGES", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
